version: "3.9"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  receiver:
    build:
      context: .
      dockerfile: receiver/Dockerfile
    environment:
      - RAW_SAMPLE_RATE=48000
      - REDIS_URL=redis://redis:6379

    volumes:
      - ./data:/app/data
      - ./models:/app/models:ro
    depends_on:
      - redis
    profiles: ["hardware"]
    devices:
      - /dev/bus/usb:/dev/bus/usb

  controller:
    build:
      context: .
      dockerfile: controller/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./models:/app/models:ro
    depends_on:
      - redis

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_HOST=controller
      - VITE_API_PORT=8000
    depends_on:
      - controller
